!function(e,t,a){function n(){c(".heart{width: 10px;height: 10px;position: fixed;background: #f00;transform: rotate(45deg);-webkit-transform: rotate(45deg);-moz-transform: rotate(45deg);}.heart:after,.heart:before{content: '';width: inherit;height: inherit;background: inherit;border-radius: 50%;-webkit-border-radius: 50%;-moz-border-radius: 50%;position: fixed;}.heart:after{top: -5px;}.heart:before{left: -5px;}"),o(),r()}function r(){for(var e=0;e<d.length;e++)d[e].alpha<=0?(t.body.removeChild(d[e].el),d.splice(e,1)):(d[e].y--,d[e].scale+=.004,d[e].alpha-=.013,d[e].el.style.cssText="left:"+d[e].x+"px;top:"+d[e].y+"px;opacity:"+d[e].alpha+";transform:scale("+d[e].scale+","+d[e].scale+") rotate(45deg);background:"+d[e].color+";z-index:99999");requestAnimationFrame(r)}function o(){var t="function"==typeof e.onclick&&e.onclick;e.onclick=function(e){t&&t(),i(e)}}function i(e){var a=t.createElement("div");a.className="heart",d.push({el:a,x:e.clientX-5,y:e.clientY-5,scale:1,alpha:1,color:s()}),t.body.appendChild(a)}function c(e){var a=t.createElement("style");a.type="text/css";try{a.appendChild(t.createTextNode(e))}catch(t){a.styleSheet.cssText=e}t.getElementsByTagName("head")[0].appendChild(a)}function s(){return"rgb("+~~(255*Math.random())+","+~~(255*Math.random())+","+~~(255*Math.random())+")"}var d=[];e.requestAnimationFrame=function(){return e.requestAnimationFrame||e.webkitRequestAnimationFrame||e.mozRequestAnimationFrame||e.oRequestAnimationFrame||e.msRequestAnimationFrame||function(e){setTimeout(e,1e3/60)}}(),n()}(window,document);




TITLE: this is an example of a path analysis
DATA: FILE IS C:\Users\Maggie_Z\Desktop\数据\结果\修正后的数据.dat;
VARIABLE: NAMES ARE a1 a2 a4 a6 b12 b13 b14 c18 c19;
USEVARIABLE = inc medu mocc dif mdistr mdisor mtra imp exp;
DEFINE:  inc=a1;
         medu=a2;
         mocc=a4;
         dif=a6;
         mdistr=b12;
         mdisor=b13;
         mtra=b14;
         imp=c18;
         exp=c19;
ANALYSIS: Bootstrap=1000;
MODEL: imp on inc mdistr;
         imp on inc mdisor;
         imp on inc mtra;
         imp on medu mdistr;
         imp on medu mdisor;
         imp on medu mtra;
         imp on mocc mdistr;
         imp on mocc mdisor;
         imp on mocc mtra;
         imp on dif mdistr;
         imp on dif mdisor;
         imp on dif mtra;
         exp on inc mdistr;
         exp on inc mdistr;
         exp on inc mtra;
         exp on medu mdistr;
         exp on medu mdisor;
         exp on medu mtra;
         exp on mocc mdistr;
         exp on mocc mdisor;
         exp on mocc mtra;
         exp on dif mdistr;
         exp on dif mdisor;
         exp on dif mtra;
         mdistr on inc;
         mdistr on medu;
         mdistr on mocc;
         mdistr on dif;
         mdisor on inc;
         mdisor on medu;
         mdisor on mocc;
         mdisor on dif;
         mtra on inc;
         mtra on medu;
         mtra on mocc;
         mtra on dif;
         mdistr with mdisor;
         mdistr with mtra;
         mdisor with mtra;
  MODEL INDIRECT:imp ind mdistr inc;
                 imp ind mdistr medu;
                 imp ind mdistr mocc;
                 imp ind mdistr dif;
                 imp ind mdisor inc;
                 imp ind mdisor medu;
                 imp ind mdisor mocc;
                 imp ind mdisor dif;
                 imp ind mtra inc;
                 imp ind mtra medu;
                 imp ind mtra mocc;
                 imp ind mtra dif;
                 exp ind mdistr inc;
                 exp ind mdistr medu;
                 exp ind mdistr mocc;
